### ISSUE TITLE
Meeting notes TODO

### ISSUE THREAD

**Issue by belgattitude** [contredanse/mfts#1]
- First review (bapt/flo)

  - [x] **Data `data-pages.json`**
      - [x] New attribute: `loop` to control infinite loops of pages videos
      - [x] New attribute: `loop_number` to control number of iterations
      - [x] New attribute: `speed_control` to display video speed control (*was abandonned after*)
  - [x] **Homepage/Landing page**
    - [x] Design: Broaden click to entire text block -> goto intro  
    - [x] Design: language to right upper corner  
    - [x] Design: Video background (2tubes)
    - [x] Feature: Remove speed behaviour onMouseOver
    - [x] Feature add Fullscreen
  - [x] **Introduction page**
    - [x] Skip intro -> go to navigation (helix or page list / quid mobile ?)    
  - [x] **Topbar**
    - [x] Remove top icons in favour of sidebar
    - [x] Design: Page breadcrumb (menu sections and title )should be in the top area (react portal).
    - [x] AutoHide page breadcrumb on inactivity
    - [x] Design: Keep only hamburger menu and helix icons
  - [x] **Sidebar (main menu)**
    - [ ] Feature: Side navigation opens submenu 
       - [x] Home
       - [x] About 
       - [x] Content
       - [x] Credits 
       - [x] Biography
       - [x] (Login/Logout)
       - [x] Language and Link contredanse 
       - [x] Copyright       
  - [x] **Page**
    - [x] Design: margin-bottom to prevent video to overlap with controls
  - [x] **PageList**
      - [x] Design: Move the search to the top (new appbar)    
  - [x] **Player**       
    - [x] On play end, show overlay :
      - [ ] Strategy choice (next / reload / timeout ?)    
    - [x] Controlbar
      - [x] Playback speed control 
        - [x] If video is muted or explicit definition `speed_control` in data.
      - [x] Translated tooltips for buttons (play, pause, show subtitles...)
      - [x] AutoHide controlbar on inactivity   
      - [x] Add fullscreen icon + support (redux)
      - [x] SVG icons:
        - [x] <u>Contredanse</u>
          - [x] **Abandoned** play/pause maybe ? 
          - [x] **Abandoned** looping on/off variants
          - [x] subtitles on/off variants, maybe ?
      - [x] (abandonned) Visually indicate that it's autoloop or looping iterations
      - [x] Change order of icons
          - [x] Previous to the left... (greyed if not availble)         
  - [x] **Static pages**
    - [x] Markdown for pages (by contredanse)
      - [x] Bibliography
      - [x] Credits
      - [x] Biography
      - [x] Biblio
      - [x] Copyright

**Comment by belgattitude** [comment]
- [ ] Intro -> helix
- [ ] Quand fin video, le player soir il affiche replay soit caché 
- [ ] Timer -> alors il revient au menu spirale.
      (Mobile - la spirale sur mobile = la liste -> 10 secondes - Nice to have)
- [ ] NTH (hide also hamburger and helix)
- [ ] A rechercher: sur IOS fullscreen disable fullscreen button (https://caniuse.com/#feat=fullscreen)
- [ ] A rechercher: 
- [ ] Son x1.5, x0.5
